### PR TITLE
Language updates – mostly to CCIP Sucker, and some throughout.

### PR DESCRIPTION
**Pull request by filipviz**
Let's get this one merged ASAP (as well as #41 & #40) – otherwise, branches will diverge and we'll have to re-do lots of work.

### CODE REVIEW

**Comment by simplemachine92** [comment]
This should have been based on #40- it's up to date with master and adapted for lastest versions.

**Comment by filipviz** [comment]
image

I was [lied to](https://discord.com/channels/775859454780244028/786985806396784690/1260967880921583687)! @simplemachine92 do you need me to do something or can you resolve this?

**Comment by filipviz** [comment]
Bump @simplemachine92 – can we merge?

**Comment by simplemachine92** [comment]
> Bump @simplemachine92 – can we merge?

change the base branch to #40 and see how that looks

**Comment by filipviz** [comment]
@simplemachine92 I'm busy with all of the other repos. Could you take care of refitting as needed? Otherwise, I'll get back to this later.

**Comment by mejango** [comment]
Fixed in #58

**Pull request closed without merging**
